import { createRouter, createWebHistory } from 'vue-router'
import HomeView from '../views/HomeView.vue'
import CourseView from '../views/CourseView.vue'
import LessonPulseView from '../views/LessonPulseView.vue'
import LessonBeatsView from '../views/LessonBeatsView.vue'

const routes = [
  { path: '/', name: 'home', component: HomeView },
  { path: '/course', name: 'course', component: CourseView },
  { path: '/course/pulse/lesson-1', name: 'lesson-pulse-1', component: LessonPulseView, meta: { title: 'Урок 1: Пульс' } },
  { path: '/course/beats/lesson-2', name: 'lesson-beats-2', component: LessonBeatsView, meta: { title: 'Урок 2: Доли и деление доли' } },
  { path: '/course/syncopation/lesson-3', name: 'lesson-syncopation-3', component: () => import('../views/LessonSyncopationView.vue'), meta: { title: 'Урок 3: Синкопа' } },
  { path: '/course/pitch-direction/lesson-4', name: 'lesson-pitch-4', component: () => import('../views/LessonPitchDirectionView.vue'), meta: { title: 'Урок 4: Направление мелодии' } },
  { path: '/course/octave/lesson-5', name: 'lesson-octave-5', component: () => import('../views/LessonOctaveView.vue'), meta: { title: 'Урок 5: Октава и регистр' } },
  { path: '/course/piano-roll/lesson-6', name: 'lesson-piano-roll-6', component: () => import('../views/LessonPianoRollView.vue'), meta: { title: 'Урок 6: Ориентация на piano roll' } },
  { path: '/course/intervals-close/lesson-7', name: 'lesson-intervals-7', component: () => import('../views/LessonIntervalsCloseView.vue'), meta: { title: 'Урок 7: Близкие интервалы' } },
  { path: '/course/intervals-far/lesson-8', name: 'lesson-intervals-8', component: () => import('../views/LessonIntervalsFarView.vue'), meta: { title: 'Урок 8: Дальние интервалы' } },
  { path: '/course/tonic/lesson-9', name: 'lesson-tonic-9', component: () => import('../views/LessonTonicView.vue'), meta: { title: 'Урок 9: Тональный центр' } },
  { path: '/course/scale-steps/lesson-10', name: 'lesson-scale-10', component: () => import('../views/LessonScaleStepsView.vue'), meta: { title: 'Урок 10: Ступени гаммы' } },
  { path: '/course/triads/lesson-11', name: 'lesson-triads-11', component: () => import('../views/LessonTriadsView.vue'), meta: { title: 'Урок 11: Трезвучия' } },
  { path: '/course/chords-application/lesson-12', name: 'lesson-chords-12', component: () => import('../views/LessonChordsApplicationView.vue'), meta: { title: 'Урок 12: Применение аккордов' } },
  { path: '/course/dominant-seven/lesson-13', name: 'lesson-dominant-13', component: () => import('../views/LessonDominantSevenView.vue'), meta: { title: 'Урок 13: Доминанта-септ' } },
  { path: '/course/minor-seven/lesson-14', name: 'lesson-minor-14', component: () => import('../views/LessonMinor7View.vue'), meta: { title: 'Урок 14: Минорные аккорды с добавками' } },
  { path: '/course/modes/lesson-15', name: 'lesson-modes-15', component: () => import('../views/LessonModesView.vue'), meta: { title: 'Урок 15: Натуральные лады' } },
  { path: '/course/triton/lesson-16', name: 'lesson-triton-16', component: () => import('../views/LessonTritonView.vue'), meta: { title: 'Урок 16: Тритон' } },
  { path: '/course/minor-progression/lesson-17', name: 'lesson-minor-17', component: () => import('../views/LessonMinorProgressionView.vue'), meta: { title: 'Урок 17: Прогрессия i-VII в миноре' } },
  { path: '/course/melody-phrasing/lesson-18', name: 'lesson-melody-18', component: () => import('../views/LessonMelodyPhrasingView.vue'), meta: { title: 'Урок 18: Мелодическое движение и фразировка' } },
  { path: '/course/breath-pause/lesson-19', name: 'lesson-breath-19', component: () => import('../views/LessonBreathPauseView.vue'), meta: { title: 'Урок 19: Дыхание и пауза' } },
  { path: '/course/voice-leading/lesson-20', name: 'lesson-voice-20', component: () => import('../views/LessonVoiceLeadingView.vue'), meta: { title: 'Урок 20: Правильный голосовой ход' } },
  { path: '/course/pentatonic/lesson-21', name: 'lesson-pent-21', component: () => import('../views/LessonPentatonicView.vue'), meta: { title: 'Урок 21: Пентатоника' } },
  { path: '/course/synth-modulation/lesson-22', name: 'lesson-synth-22', component: () => import('../views/LessonSynthModulationView.vue'), meta: { title: 'Урок 22: Синтезатор и модуляция' } },
  { path: '/course/groove-shuffle/lesson-23', name: 'lesson-groove-23', component: () => import('../views/LessonGrooveShuffleView.vue'), meta: { title: 'Урок 23: Groove и shuffle ритм' } },
  { path: '/course/loop-creation/lesson-24', name: 'lesson-loop-24', component: () => import('../views/LessonLoopCreationView.vue'), meta: { title: 'Урок 24: Создание лупа из аккордов' } },
  { path: '/course/practice-final/lesson-25', name: 'lesson-final-25', component: () => import('../views/LessonPracticeFinalView.vue'), meta: { title: 'Урок 25: Практика — пишем свой трек' } },
  { path: '/course/solfege-syllables/lesson-26', name: 'lesson-solfege-26', component: () => import('../views/LessonSolfegeSyllablesView.vue'), meta: { title: 'Урок 26: Сольфеджио слоги' } },
  { path: '/course/keys/lesson-27', name: 'lesson-keys-27', component: () => import('../views/LessonKeysView.vue'), meta: { title: 'Урок 27: Ключи и тональный центр' } },
  { path: '/course/chord-functions/lesson-28', name: 'lesson-chord-functions-28', component: () => import('../views/LessonChordFunctionsView.vue'), meta: { title: 'Урок 28: Функции аккордов' } },
  { path: '/course/melody-harmony/lesson-29', name: 'lesson-melody-harmony-29', component: () => import('../views/LessonMelodyHarmonyView.vue'), meta: { title: 'Урок 29: Мелодия над гармонией' } },
  { path: '/course/interval-dictation/lesson-30', name: 'lesson-interval-dictation-30', component: () => import('../views/LessonIntervalDictationView.vue'), meta: { title: 'Урок 30: Интервальная диктовка' } },
  { path: '/course/melodic-dictation/lesson-31', name: 'lesson-melodic-dictation-31', component: () => import('../views/LessonMelodicDictationView.vue'), meta: { title: 'Урок 31: Мелодическая диктовка' } },
  { path: '/course/rhythm/division/lesson-32', name: 'lesson-rhythm-32', component: () => import('../views/LessonRhythmDivisionView.vue'), meta: { title: 'Урок 32: Деление доли' } },
  { path: '/course/rhythm/dots-ties/lesson-33', name: 'lesson-rhythm-33', component: () => import('../views/LessonRhythmDotsTiesView.vue'), meta: { title: 'Урок 33: Точки и лиги' } },
  { path: '/course/rhythm/syncopation-advanced/lesson-34', name: 'lesson-rhythm-34', component: () => import('../views/LessonRhythmSyncopationAdvancedView.vue'), meta: { title: 'Урок 34: Синкопа — продвинутый' } },
  { path: '/course/rhythm/triplets/lesson-35', name: 'lesson-rhythm-35', component: () => import('../views/LessonRhythmTripletsView.vue'), meta: { title: 'Урок 35: Триоли и деления' } },
  { path: '/course/rhythm/swing/lesson-36', name: 'lesson-rhythm-36', component: () => import('../views/LessonRhythmSwingView.vue'), meta: { title: 'Урок 36: Свинг и shuffle' } },
  { path: '/course/rhythm/compound-meters/lesson-37', name: 'lesson-rhythm-37', component: () => import('../views/LessonCompoundMetersView.vue'), meta: { title: 'Урок 37: Составные размеры' } },
  { path: '/course/rhythm/odd-meters/lesson-38', name: 'lesson-rhythm-38', component: () => import('../views/LessonOddMetersView.vue'), meta: { title: 'Урок 38: Нечётные размеры' } },
  { path: '/course/rhythm/polyrhythm/lesson-39', name: 'lesson-rhythm-39', component: () => import('../views/LessonPolyrhythmView.vue'), meta: { title: 'Урок 39: Полиритмия' } },
  { path: '/course/rhythm/groove/lesson-40', name: 'lesson-rhythm-40', component: () => import('../views/LessonGrooveMicrotimingView.vue'), meta: { title: 'Урок 40: Грув и микротайминг' } },
  { path: '/course/rhythm/piano-roll/lesson-41', name: 'lesson-rhythm-41', component: () => import('../views/LessonPianoRollRhythmView.vue'), meta: { title: 'Урок 41: Ритм в piano roll' } },
  // --- Mode and Tonality lessons (42-51)
  { path: '/course/minor-variants/lesson-42', name: 'lesson-42', component: () => import('../views/LessonMinorVariantsView.vue'), meta: { title: 'Натуральный, гармонический и мелодический минор', description: 'Разница между вариантами минора и практические примеры.' } },
  { path: '/course/scale-steps/lesson-43', name: 'lesson-43', component: () => import('../views/LessonScaleTendenciesView.vue'), meta: { title: 'Ступени лада и их тяготения', description: 'Функции каждой ступени и их притяжение.' } },
  { path: '/course/parallel-keys/lesson-44', name: 'lesson-44', component: () => import('../views/LessonParallelKeysView.vue'), meta: { title: 'Параллельные и одноимённые тональности', description: 'Отличия и как использовать в аранжировке.' } },
  { path: '/course/circle-fifths/lesson-45', name: 'lesson-45', component: () => import('../views/LessonCircleFifthsView.vue'), meta: { title: 'Квинтовый круг на практике', description: 'Практическое использование круга квинт для транспозиции и подбора аккордов.' } },
  { path: '/course/transposition/lesson-46', name: 'lesson-46', component: () => import('../views/LessonTranspositionView.vue'), meta: { title: 'Транспонирование мелодии и аккордов', description: 'Методики быстрого транспонирования в голове и DAW.' } },
  { path: '/course/modes/lesson-47', name: 'lesson-47', component: () => import('../views/LessonSevenModesView.vue'), meta: { title: 'Семь диатонических ладов', description: 'Краткие характеристики и примеры использования.' } },
  { path: '/course/pentatonic/lesson-48', name: 'lesson-48', component: () => import('../views/LessonPentatonicAppliedView.vue'), meta: { title: 'Пентатоника', description: 'Применение пентатоники в мелодии и импровизации.' } },
  { path: '/course/blues-scale/lesson-49', name: 'lesson-49', component: () => import('../views/LessonBluesScaleView.vue'), meta: { title: 'Блюзовый звукоряд', description: 'Blue notes и их роль в фразировке.' } },
  { path: '/course/alt-scales/lesson-50', name: 'lesson-50', component: () => import('../views/LessonAltScalesView.vue'), meta: { title: 'Целотонный и уменьшённый звукоряд', description: 'Whole-tone и diminished scales — где и зачем.' } },
  { path: '/course/mode-choice/lesson-51', name: 'lesson-51', component: () => import('../views/LessonModeChoiceView.vue'), meta: { title: 'Выбор лада для нужного характера трека', description: 'Практические рекомендации при создании трека.' } },

  // --- Harmony and Chords (52-71)
  { path: '/course/triads/lesson-52', name: 'lesson-52', component: () => import('../views/LessonTriadTypesView.vue'), meta: { title: 'Трезвучия всех видов', description: 'Строение, качество и примеры.' } },
  { path: '/course/scale-chords/lesson-53', name: 'lesson-53', component: () => import('../views/LessonMajorScaleChordsView.vue'), meta: { title: 'Аккорды на каждой ступени мажора', description: 'Функции каждого аккорда в тональности.' } },
  { path: '/course/minor-chords/lesson-54', name: 'lesson-54', component: () => import('../views/LessonMinorScaleChordsView.vue'), meta: { title: 'Аккорды в минорной тональности', description: 'Особенности аккордов в миноре.' } },
  { path: '/course/triad-inversions/lesson-55', name: 'lesson-55', component: () => import('../views/LessonTriadInversionsView.vue'), meta: { title: 'Обращения трезвучий', description: 'Как и зачем использовать обращения.' } },
  { path: '/course/seventh-chords/lesson-56', name: 'lesson-56', component: () => import('../views/LessonSeventhChordTypesView.vue'), meta: { title: 'Септаккорды', description: 'Структура и практическое применение.' } },
  { path: '/course/seventh-inversions/lesson-57', name: 'lesson-57', component: () => import('../views/LessonSeventhInversionsView.vue'), meta: { title: 'Обращения септаккордов', description: 'Варианты обращения и голосоведение.' } },
  { path: '/course/functions/lesson-58', name: 'lesson-58', component: () => import('../views/LessonHarmonicFunctionsView.vue'), meta: { title: 'Функции: тоника, субдоминанта, доминанта', description: 'Роли аккордов и разрешения.' } },
  { path: '/course/harmonic-rhythm/lesson-59', name: 'lesson-59', component: () => import('../views/LessonHarmonicRhythmView.vue'), meta: { title: 'Гармонический ритм', description: 'Скорость смены аккордов и её влияние на форму.' } },
  { path: '/course/cadences/lesson-60', name: 'lesson-60', component: () => import('../views/LessonCadencesView.vue'), meta: { title: 'Каденции', description: 'Типы каденций и их музыкальная роль.' } },
  { path: '/course/voice-leading/lesson-61', name: 'lesson-61', component: () => import('../views/LessonChordVoiceLeadingView.vue'), meta: { title: 'Голосоведение между аккордами', description: 'Плавность переходов и приёмы.' } },
  { path: '/course/pedals/lesson-62', name: 'lesson-62', component: () => import('../views/LessonPedalOstinatoView.vue'), meta: { title: 'Педальный тон и остинато', description: 'Как создавать устойчивую гармоническую базу.' } },
  { path: '/course/contructions/lesson-63', name: 'lesson-63', component: () => import('../views/LessonChordExtensionsView.vue'), meta: { title: 'Аккордовые расширения: 9, 11, 13', description: 'Добавление цвета и напряжения.' } },
  { path: '/course/sus-add/lesson-64', name: 'lesson-64', component: () => import('../views/LessonSusAddChordsView.vue'), meta: { title: 'Sus2, sus4 и add-аккорды', description: 'Упрощённое добавление цвета в аккорды.' } },
  { path: '/course/slash-chords/lesson-65', name: 'lesson-65', component: () => import('../views/LessonSlashChordsView.vue'), meta: { title: 'Slash chords и басовая нота', description: 'Применение и создание интересных басовых ходов.' } },
  { path: '/course/secondary-dominants/lesson-66', name: 'lesson-66', component: () => import('../views/LessonSecondaryDominantsView.vue'), meta: { title: 'Вторичные доминанты', description: 'Функция и примеры использования.' } },
  { path: '/course/modal-interchange/lesson-67', name: 'lesson-67', component: () => import('../views/LessonModalInterchangeView.vue'), meta: { title: 'Заимствованные аккорды (modal interchange)', description: 'Как и когда заимствовать аккорды из параллельных ладов.' } },
  { path: '/course/deceptive/lesson-68', name: 'lesson-68', component: () => import('../views/LessonDeceptiveResolutionView.vue'), meta: { title: 'Обманные разрешения', description: 'Как создавать неожиданные, но музыкальные переходы.' } },
  { path: '/course/diminished/lesson-69', name: 'lesson-69', component: () => import('../views/LessonPassingDiminishedView.vue'), meta: { title: 'Уменьшённые проходящие аккорды', description: 'Использование diminished для украшения прогрессий.' } },
  { path: '/course/reharmonization/lesson-70', name: 'lesson-70', component: () => import('../views/LessonReharmonizationView.vue'), meta: { title: 'Ре-гармонизация простой мелодии', description: 'Практический пример на ре-гармонизации.' } },
  { path: '/course/create-progression/lesson-71', name: 'lesson-71', component: () => import('../views/LessonCreateProgressionView.vue'), meta: { title: 'Создание собственной аккордовой последовательности', description: 'Пошаговый подход к созданию прогрессии.' } },

  // --- Melody (72-85)
  { path: '/course/motif/lesson-72', name: 'lesson-72', component: () => import('../views/LessonMotifView.vue'), meta: { title: 'Мотив как минимальная музыкальная идея', description: 'Работа с короткими идеями и их развитием.' } },
  { path: '/course/repetition/lesson-73', name: 'lesson-73', component: () => import('../views/LessonMotifRepetitionView.vue'), meta: { title: 'Повтор и изменение мотива', description: 'Техники варьирования мотивов.' } },
  { path: '/course/sequence/lesson-74', name: 'lesson-74', component: () => import('../views/LessonSequenceView.vue'), meta: { title: 'Секвенция', description: 'Простые и сложные секвенции в мелодии.' } },
  { path: '/course/inversion/lesson-75', name: 'lesson-75', component: () => import('../views/LessonMotifInversionView.vue'), meta: { title: 'Инверсия, увеличение и уменьшение', description: 'Манипуляции с мотивом.' } },
  { path: '/course/phrase/lesson-76', name: 'lesson-76', component: () => import('../views/LessonPhraseView.vue'), meta: { title: 'Фраза и музыкальное предложение', description: 'Структура фразы и её компоненты.' } },
  { path: '/course/open-closed/lesson-77', name: 'lesson-77', component: () => import('../views/LessonOpenClosedPhrasesView.vue'), meta: { title: 'Открытые и закрытые фразы', description: 'Как строить завершённые мелодические мысли.' } },
  { path: '/course/notes/lesson-78', name: 'lesson-78', component: () => import('../views/LessonChordTonesPassingView.vue'), meta: { title: 'Опорные и проходящие ноты', description: 'Функции нот в мелодии.' } },
  { path: '/course/neighbor/lesson-79', name: 'lesson-79', component: () => import('../views/LessonSuspensionsNeighborsView.vue'), meta: { title: 'Задержания и соседние звуки', description: 'Украшения и их эффект.' } },
  { path: '/course/tension/lesson-80', name: 'lesson-80', component: () => import('../views/LessonMelodicTensionView.vue'), meta: { title: 'Напряжение и разрешение в мелодии', description: 'Создание драматургии в мелодии.' } },
  { path: '/course/melody-harmony-link/lesson-81', name: 'lesson-81', component: () => import('../views/LessonMelodyHarmonyLinkView.vue'), meta: { title: 'Связь мелодии с аккордом', description: 'Как мелодия отражает гармонию.' } },
  { path: '/course/melodic-rhythm/lesson-82', name: 'lesson-82', component: () => import('../views/LessonMelodicRhythmView.vue'), meta: { title: 'Мелодический ритм', description: 'Ритм внутри мелодии и акцентирование.' } },
  { path: '/course/hook/lesson-83', name: 'lesson-83', component: () => import('../views/LessonHookView.vue'), meta: { title: 'Создание хука', description: 'Техники написания запоминающихся фраз.' } },
  { path: '/course/variation/lesson-84', name: 'lesson-84', component: () => import('../views/LessonMelodicVariationView.vue'), meta: { title: 'Вариации мелодии без потери узнаваемости', description: 'Сохранение идентичности при изменениях.' } },
  { path: '/course/countermelody/lesson-85', name: 'lesson-85', component: () => import('../views/LessonCountermelodyView.vue'), meta: { title: 'Контрмелодия', description: 'Создание второй линии, дополняющей основную.' } },

  // --- Bass (86-95)
  { path: '/course/bass/root/lesson-86', name: 'lesson-86', component: () => import('../views/LessonRootBassView.vue'), meta: { title: 'Корневая басовая линия', description: 'Простые корневые басы и их функция.' } },
  { path: '/course/bass/chordtones/lesson-87', name: 'lesson-87', component: () => import('../views/LessonChordToneBassView.vue'), meta: { title: 'Бас по звукам аккорда', description: 'Как строить басовые партии, опираясь на аккорды.' } },
  { path: '/course/bass/passing/lesson-88', name: 'lesson-88', component: () => import('../views/LessonPassingChromaticBassView.vue'), meta: { title: 'Проходящие и хроматические ноты', description: 'Движение баса через хроматику.' } },
  { path: '/course/bass/ostinato/lesson-89', name: 'lesson-89', component: () => import('../views/LessonOstinatoBassView.vue'), meta: { title: 'Остинатный бас', description: 'Создание повторяющихся басовых паттернов.' } },
  { path: '/course/bass/counterpoint/lesson-90', name: 'lesson-90', component: () => import('../views/LessonBassCounterpointView.vue'), meta: { title: 'Контрапункт баса и мелодии', description: 'Взаимодействие нижней и верхней линии.' } },
  { path: '/course/bass/kick/lesson-91', name: 'lesson-91', component: () => import('../views/LessonBassKickView.vue'), meta: { title: 'Связь баса с бочкой', description: 'Как синхронизировать бас и ударную секцию.' } },
  { path: '/course/bass/rhythm-contrast/lesson-92', name: 'lesson-92', component: () => import('../views/LessonBassRhythmContrastView.vue'), meta: { title: 'Ритмический контраст баса и ударных', description: 'Создание интереса через контраст.' } },
  { path: '/course/bass/variations/lesson-93', name: 'lesson-93', component: () => import('../views/LessonBassVariationsView.vue'), meta: { title: 'Вариации басовой линии', description: 'Методы варьирования повторяющихся линий.' } },
  { path: '/course/bass/pedal/lesson-94', name: 'lesson-94', component: () => import('../views/LessonPedalBassDroneView.vue'), meta: { title: 'Pedal bass и drone', description: 'Длительные ноты и дроны как гармоническая база.' } },
  { path: '/course/bass/function/lesson-95', name: 'lesson-95', component: () => import('../views/LessonBassHarmonicMotionView.vue'), meta: { title: 'Бас как источник гармонического движения', description: 'Использование баса для создания прогрессии.' } },

  // --- Form and Arrangement (96-107)
  { path: '/course/form/lesson-96', name: 'lesson-96', component: () => import('../views/LessonFormHierarchyView.vue'), meta: { title: 'Мотив, фраза, период и секция', description: 'Анализ базовой формы композиции.' } },
  { path: '/course/form/ab-lesson/lesson-97', name: 'lesson-97', component: () => import('../views/LessonSongFormsView.vue'), meta: { title: 'Формы AB, ABA и AABA', description: 'Структурные паттерны и их влияние на слушателя.' } },
  { path: '/course/form/structure/lesson-98', name: 'lesson-98', component: () => import('../views/LessonSongSectionsView.vue'), meta: { title: 'Куплет, припев, бридж и инструментальная секция', description: 'Компоненты современной песни.' } },
  { path: '/course/form/intro-outro/lesson-99', name: 'lesson-99', component: () => import('../views/LessonIntroOutroView.vue'), meta: { title: 'Intro и outro', description: 'Как начать и закончить трек.' } },
  { path: '/course/form/build-drop/lesson-100', name: 'lesson-100', component: () => import('../views/LessonBuildDropView.vue'), meta: { title: 'Build-up, drop и breakdown', description: 'Динамическая структура для электронной музыки.' } },
  { path: '/course/form/repeat-contrast/lesson-101', name: 'lesson-101', component: () => import('../views/LessonRepetitionContrastView.vue'), meta: { title: 'Повторение и контраст', description: 'Баланс знакомости и новизны.' } },
  { path: '/course/form/loop-development/lesson-102', name: 'lesson-102', component: () => import('../views/LessonLoopDevelopmentView.vue'), meta: { title: 'Развитие восьмитактового loop', description: 'Методы развития короткой идеи.' } },
  { path: '/course/form/layering/lesson-103', name: 'lesson-103', component: () => import('../views/LessonLayeringView.vue'), meta: { title: 'Добавление и удаление музыкальных слоёв', description: 'Техники аранжировки и управления плотностью.' } },
  { path: '/course/form/texture/lesson-104', name: 'lesson-104', component: () => import('../views/LessonTextureView.vue'), meta: { title: 'Плотность, регистр и фактура', description: 'Как управлять звуковой текстурой.' } },
  { path: '/course/form/dynamics/lesson-105', name: 'lesson-105', component: () => import('../views/LessonDynamicArcView.vue'), meta: { title: 'Динамическая и эмоциональная дуга', description: 'Построение эмоционального развития.' } },
  { path: '/course/form/transitions/lesson-106', name: 'lesson-106', component: () => import('../views/LessonTransitionsView.vue'), meta: { title: 'Переходы между разделами', description: 'Кросс-фейды, фильтры и эффекты как переходы.' } },
  { path: '/course/form/finish/lesson-107', name: 'lesson-107', component: () => import('../views/LessonFullTrackView.vue'), meta: { title: 'Создание полного трека из короткой идеи', description: 'От мотива до готового трека — шаги.' } },

  // --- Ear Training (108-123)
  { path: '/course/ear/direction/lesson-108', name: 'lesson-108', component: () => import('../views/LessonEarDirectionView.vue'), meta: { title: 'Определение направления мелодии', description: 'Практика распознавания вверх/вниз.' } },
  { path: '/course/ear/intervals/lesson-109', name: 'lesson-109', component: () => import('../views/LessonEarIntervalsView.vue'), meta: { title: 'Определение интервалов на слух', description: 'Интерактивные упражнения на интервалы.' } },
  { path: '/course/ear/singing-scale/lesson-110', name: 'lesson-110', component: () => import('../views/LessonEarSingingScaleView.vue'), meta: { title: 'Пение ступеней относительно тоники', description: 'Вокальные упражнения для памяти ступеней.' } },
  { path: '/course/ear/sing-melody/lesson-111', name: 'lesson-111', component: () => import('../views/LessonEarSingMelodyView.vue'), meta: { title: 'Пение коротких мелодических оборотов', description: 'Запоминание и воспроизведение коротких фраз.' } },
  { path: '/course/ear/rhythm-dictation/lesson-112', name: 'lesson-112', component: () => import('../views/LessonEarRhythmDictationView.vue'), meta: { title: 'Ритмический диктант', description: 'Тренируем слух на ритм.' } },
  { path: '/course/ear/melodic-dictation/lesson-113', name: 'lesson-113', component: () => import('../views/LessonEarMelodicDictationView.vue'), meta: { title: 'Мелодический диктант', description: 'Запись услышанной мелодии.' } },
  { path: '/course/ear/major-minor/lesson-114', name: 'lesson-114', component: () => import('../views/LessonEarMajorMinorView.vue'), meta: { title: 'Определение мажора и минора', description: 'Быстрая классификация по звучанию.' } },
  { path: '/course/ear/triad-quality/lesson-115', name: 'lesson-115', component: () => import('../views/LessonEarTriadQualityView.vue'), meta: { title: 'Определение вида трезвучия', description: 'Упражнения на мажор/минор/увелич.' } },
  { path: '/course/ear/inversion/lesson-116', name: 'lesson-116', component: () => import('../views/LessonEarInversionView.vue'), meta: { title: 'Определение обращения аккорда', description: 'Слушаем и различаем обращения.' } },
  { path: '/course/ear/seventh/lesson-117', name: 'lesson-117', component: () => import('../views/LessonEarSeventhView.vue'), meta: { title: 'Определение септаккордов', description: 'Практика различения 7th аккордов.' } },
  { path: '/course/ear/functions/lesson-118', name: 'lesson-118', component: () => import('../views/LessonEarFunctionsView.vue'), meta: { title: 'Определение функций I, IV и V', description: 'Слушаем роль аккордов в контексте.' } },
  { path: '/course/ear/progressions/lesson-119', name: 'lesson-119', component: () => import('../views/LessonEarProgressionsView.vue'), meta: { title: 'Определение аккордовых последовательностей', description: 'Тренируем слух на последовательности.' } },
  { path: '/course/ear/bass/lesson-120', name: 'lesson-120', component: () => import('../views/LessonEarBassView.vue'), meta: { title: 'Определение басовой линии', description: 'Слух на низкие партии и их движение.' } },
  { path: '/course/ear/transcribe-melody/lesson-121', name: 'lesson-121', component: () => import('../views/LessonEarTranscribeMelodyView.vue'), meta: { title: 'Снятие короткой мелодии на слух', description: 'Практическое задание по записи мелодии.' } },
  { path: '/course/ear/transcribe-chords/lesson-122', name: 'lesson-122', component: () => import('../views/LessonEarTranscribeChordsView.vue'), meta: { title: 'Снятие аккордов реального трека', description: 'Разбор референса и выписка аккордов.' } },
  { path: '/course/ear/pianoroll/lesson-123', name: 'lesson-123', component: () => import('../views/LessonEarPianoRollView.vue'), meta: { title: 'Воспроизведение услышанного в piano roll', description: 'Перевод услышанного в MIDI.' } },

  // --- DAW practicals (124-137)
  { path: '/course/daw/pitch-lesson/lesson-124', name: 'lesson-124', component: () => import('../views/LessonPianoRollOctavesView.vue'), meta: { title: 'Ноты и октавы в piano roll', description: 'Работа с октавами и расположением нот.' } },
  { path: '/course/daw/tonality/lesson-125', name: 'lesson-125', component: () => import('../views/LessonProjectTonalityView.vue'), meta: { title: 'Тональность проекта и подсветка гаммы', description: 'Настройка проекта под тональность и удобная подсветка.' } },
  { path: '/course/daw/transposing/lesson-126', name: 'lesson-126', component: () => import('../views/LessonMidiTransposingView.vue'), meta: { title: 'Транспонирование MIDI', description: 'Быстрые способы транспонирования треков.' } },
  { path: '/course/daw/velocity/lesson-127', name: 'lesson-127', component: () => import('../views/LessonVelocityView.vue'), meta: { title: 'Velocity как элемент музыкальной фразы', description: 'Использование velocity для выразительности.' } },
  { path: '/course/daw/duration/lesson-128', name: 'lesson-128', component: () => import('../views/LessonArticulationView.vue'), meta: { title: 'Длительность, articulation и legato', description: 'Артикуляция и её влияние на фразу.' } },
  { path: '/course/daw/quantize/lesson-129', name: 'lesson-129', component: () => import('../views/LessonQuantizeView.vue'), meta: { title: 'Quantize и последствия жёсткого выравнивания', description: 'Когда квантизация помогает, а когда нет.' } },
  { path: '/course/daw/swing/lesson-130', name: 'lesson-130', component: () => import('../views/LessonGrooveTemplatesView.vue'), meta: { title: 'Swing и groove templates', description: 'Применение swing шаблонов в DAW.' } },
  { path: '/course/daw/chords-midi/lesson-131', name: 'lesson-131', component: () => import('../views/LessonMidiChordsView.vue'), meta: { title: 'Создание аккордов в MIDI', description: 'Удобные техники для создания богатых аккордов.' } },
  { path: '/course/daw/voice-leading-midi/lesson-132', name: 'lesson-132', component: () => import('../views/LessonPianoRollVoiceLeadingView.vue'), meta: { title: 'Voice leading в piano roll', description: 'Голосоведение при работе с MIDI.' } },
  { path: '/course/daw/loop-variations/lesson-133', name: 'lesson-133', component: () => import('../views/LessonLoopVariationsView.vue'), meta: { title: 'Создание вариаций loop', description: 'Методы развития коротких идей.' } },
  { path: '/course/daw/automation/lesson-134', name: 'lesson-134', component: () => import('../views/LessonAutomationView.vue'), meta: { title: 'Automation как музыкальное развитие', description: 'Автоматизация параметров для динамики.' } },
  { path: '/course/daw/reference/lesson-135', name: 'lesson-135', component: () => import('../views/LessonReferenceTrackView.vue'), meta: { title: 'Анализ референсного трека', description: 'Как разбирать и учиться на референсах.' } },
  { path: '/course/daw/transcribe-midi/lesson-136', name: 'lesson-136', component: () => import('../views/LessonTranscribeToMidiView.vue'), meta: { title: 'Перенос услышанной идеи в MIDI', description: 'Практические приёмы транскрипции.' } },
  { path: '/course/daw/final-project/lesson-137', name: 'lesson-137', component: () => import('../views/LessonFinalProjectView.vue'), meta: { title: 'Итоговая композиция от мотива до полного трека', description: 'Проект, объединяющий все навыки.' } },
  { path: '/:pathMatch(.*)*', redirect: '/' },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) return savedPosition
    return { top: 0, left: 0, behavior: 'smooth' }
  },
})

export const lessonList = routes
  .filter((r) => r.name && r.name.startsWith('lesson'))
  .map((r) => ({ path: r.path, title: r.meta?.title || r.name }))

export default router